#!/usr/bin/env python3

import signal
import time
import sys

running = True

def handle_sigterm(signum, frame):
    global running
    print("[DUMMY] SIGTERM recibido. Cerrando limpio...")
    running = False

signal.signal(signal.SIGTERM, handle_sigterm)

print("[DUMMY] Proceso iniciado")

while running:
    print("[DUMMY] Trabajando...")
    time.sleep(1)

print("[DUMMY] Proceso finalizado")
sys.exit(0)